CREATE TABLE roles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

INSERT INTO roles (name) VALUES ('PERSONAL');
INSERT INTO roles (name) VALUES ('BUSINESS');
INSERT INTO roles (name) VALUES ('ADMIN');
